name: Python CI with Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pytest
      run: |
        pip install pytest

    - name: Lint with Ruff
      run: |
        ruff --version  # Verifying installation first
        ruff check ./tests ./particle_simulation --fix --ignore E501,F403,E402,F405,E902

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest